# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0002_auto_20180607_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Algorithm',
            new_name='Recommender',
        ),
    ]
