# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0003_auto_20180607_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='rec_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
