# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
