# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180203_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
