# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_myuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
