# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response_id',
        ),
        migrations.AlterField(
            model_name='option',
            name='option_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.IntegerField(),
        ),
    ]
