# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20180121_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(max_length=30),
        ),
    ]
