# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20180121_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='questions',
            field=models.ManyToManyField(to='surveys.Question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
