# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20180122_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
