# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20180122_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_wfbh', to='surveys.Question'),
        ),
    ]
