# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20180122_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_orders', to='surveys.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_orders', to='surveys.Question')),
            ],
        ),
    ]
