# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='started_at',
        ),
    ]
