# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_remove_surveyresponse_started_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='optionorder',
            old_name='option',
            new_name='option_id',
        ),
        migrations.RenameField(
            model_name='optionorder',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questionorder',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questionorder',
            old_name='survey',
            new_name='survey_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='survey_response',
            new_name='survey_response_id',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='survey',
            new_name='survey_id',
        ),
    ]
