# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20180123_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
    ]
