# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_remove_surveyresponse_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.TextField(),
        ),
    ]
