# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20180123_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
