# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_auto_20180123_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.IntegerField(),
        ),
    ]
