# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_auto_20180124_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionorder',
            name='order',
        ),
        migrations.AlterField(
            model_name='optionorder',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_to_question', to='surveys.Option'),
        ),
        migrations.AlterField(
            model_name='optionorder',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_option', to='surveys.Question'),
        ),
    ]
