# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_auto_20180203_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='survey_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
