# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20180204_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
