# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_auto_20180204_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('the_order',)},
        ),
        migrations.AddField(
            model_name='question',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
