# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 23:00
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_auto_20180204_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionorder',
            name='survey',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
