# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0035_auto_20180204_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='the_order',
        ),
        migrations.AlterField(
            model_name='questionorder',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_to_question', to='surveys.Survey'),
        ),
    ]
