# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0037_auto_20180211_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
