# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0039_auto_20180211_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('Between-subject', 'Between-subject'), ('Within-subject', 'Within-subject')], max_length=30),
        ),
    ]
