# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0040_auto_20180211_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='id',
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
