# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0042_survey_survey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
