# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 16:02
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0043_auto_20180324_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionorder',
            options={'ordering': ['question_order']},
        ),
        migrations.AddField(
            model_name='questionorder',
            name='question_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='questionorder',
            name='survey',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
