# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0044_auto_20180324_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionorder',
            name='question_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionorder',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_to_question', to='surveys.Survey'),
        ),
    ]
