# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0045_auto_20180324_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='question_order',
        ),
    ]
