# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0046_auto_20180324_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('option_id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('question_id',)},
        ),
    ]
