# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0047_auto_20180325_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionorder',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='questionorder',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='order_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
