# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0048_auto_20180325_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='order_by',
        ),
    ]
