# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0001_initial'),
        ('surveys', '0052_auto_20180325_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_model_to_survey', to='algos.InputModel')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_to_input_model', to='surveys.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='algorithms',
            field=models.ManyToManyField(through='surveys.Algorithm', to='algos.InputModel'),
        ),
    ]
