# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0053_auto_20180513_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='reclist_length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
