# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0054_survey_reclist_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='reclist_length',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
