# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0055_auto_20180525_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='algorithms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
