# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0056_response_algorithms'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='algorithms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
