# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0003_auto_20180607_1639'),
        ('surveys', '0057_surveyresponse_algorithms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='input_model',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='recommender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_model_to_survey', to='recsys.Recommender'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='algorithms',
            field=models.ManyToManyField(through='surveys.Algorithm', to='recsys.Recommender'),
        ),
    ]
