# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0058_auto_20180607_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='cast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='crew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='genre',
            field=models.BooleanField(default=False),
        ),
    ]
