# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0059_auto_20180607_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='recommender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommender_to_survey', to='recsys.Recommender'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_to_recommender', to='surveys.Survey'),
        ),
    ]
