# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 12:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0061_survey_input_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='ncast',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='ncrew',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='ngenres',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='input_length',
            field=models.PositiveIntegerField(default=5, help_text='This is the number of movies to select in the catalogue. Note: value range is from 1 to 10.', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='reclist_length',
            field=models.PositiveIntegerField(default=5, help_text='This is the number of movies in the recommendation list. Note: value range is from 1 to 10.', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
