# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 13:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0062_auto_20180918_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='random_first_page',
            field=models.PositiveIntegerField(default=1, help_text='This is the first catalogue page used by Random Recommender.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='survey',
            name='random_last_page',
            field=models.PositiveIntegerField(default=1, help_text='This is the last catalogue page used by Random Recommender.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='ncast',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='ncrew',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='ngenres',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
