# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0064_auto_20180926_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='algorithms',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
