# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0065_auto_20180926_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='recommendations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='user_profile',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='recommendations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user_profile',
            field=models.TextField(null=True),
        ),
    ]
