# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('vote_count', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vote_average', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=30)),
            ],
        ),
    ]
