# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('poster', models.URLField()),
                ('year', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
