# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=30)),
                ('questionNumber', models.IntegerField()),
            ],
        ),
    ]
