# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20180317_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Answer',
        ),
    ]
