# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_auto_20180317_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
