# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_surveyresponse_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valid_survey',
            field=models.BooleanField(default=False),
        ),
    ]
