# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_profile_valid_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='survey_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
